"""
Project Plan Model
"""

from dataclasses import dataclass, field


@dataclass(slots=True)
class ProjectPlan:
    """
    Plan generated by the Planner.
    """

    project_name: str = ""

    folders: list[str] = field(default_factory=list)

    files: list[str] = field(default_factory=list)

    dependencies: list[str] = field(default_factory=list)