"""
JARVIS PRO
Developer Planner

Execution Plan Model
"""

from dataclasses import dataclass, field

from brain.developer.enums import (
    Language,
    Framework,
    ProjectType,
    Workspace,
    Runtime,
    Board,
)


@dataclass(slots=True)
class ExecutionPlan:
    """
    Complete execution plan generated by the Planner.
    """

    # ----- Project Information -----

    project_name: str = ""

    language: Language | None = None

    framework: Framework | None = None

    project_type: ProjectType | None = None

    workspace: Workspace | None = None

    runtime: Runtime | None = None

    board: Board | None = None

    # ----- Planning -----

    folders: list[str] = field(default_factory=list)

    files: list[str] = field(default_factory=list)

    dependencies: list[str] = field(default_factory=list)

    tasks: list[str] = field(default_factory=list)

    notes: list[str] = field(default_factory=list)